"""initial multi-user schema

Revision ID: 4596e16062f9
Revises:
Create Date: 2026-04-30 20:05:14.250961

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4596e16062f9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=True),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column("tool_args", sa.Text(), nullable=True),
        sa.Column("tool_result", sa.Text(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_agent_actions_run", "agent_actions", ["run_id"], unique=False)
    op.create_index(
        "idx_agent_actions_time", "agent_actions", ["created_at"], unique=False
    )
    op.create_table(
        "classifier_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "trained_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("training_samples", sa.Integer(), nullable=True),
        sa.Column("positive_samples", sa.Integer(), nullable=True),
        sa.Column("negative_samples", sa.Integer(), nullable=True),
        sa.Column("cv_accuracy", sa.Float(), nullable=True),
        sa.Column("cv_precision", sa.Float(), nullable=True),
        sa.Column("cv_recall", sa.Float(), nullable=True),
        sa.Column("model_path", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=True),
        sa.Column("careers_url", sa.Text(), nullable=True),
        sa.Column(
            "ats_type", sa.Text(), server_default=sa.text("'unknown'"), nullable=False
        ),
        sa.Column("ats_slug", sa.Text(), nullable=True),
        sa.Column(
            "resolve_status",
            sa.Text(),
            server_default=sa.text("'unresolved'"),
            nullable=False,
        ),
        sa.Column(
            "resolve_attempts",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ats_type IN ('greenhouse','lever','ashby','generic','unknown')",
            name="ck_companies_ats_type",
        ),
        sa.CheckConstraint(
            "resolve_status IN ('unresolved','resolved','failed')",
            name="ck_companies_resolve_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), nullable=True),
        sa.Column("state_code", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("country_code", sa.Text(), nullable=True),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "resolution_status",
            sa.Text(),
            server_default=sa.text("'resolved'"),
            nullable=False,
        ),
        sa.Column("raw_fragment", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_name"),
    )
    op.create_index(
        "idx_locations_canonical", "locations", ["canonical_name"], unique=False
    )
    op.create_index("idx_locations_city", "locations", ["city"], unique=False)
    op.create_index(
        "idx_locations_country", "locations", ["country_code"], unique=False
    )
    op.create_index("idx_locations_region", "locations", ["region"], unique=False)
    op.create_index("idx_locations_state", "locations", ["state_code"], unique=False)
    op.create_table(
        "system_settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "crawl_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column(
            "postings_found", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "postings_new", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_postings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("title_hash", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("work_model", sa.Text(), nullable=True),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column("source_id", sa.Text(), nullable=True),
        sa.Column("source_type", sa.Text(), nullable=True),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "title_hash"),
    )
    op.create_index(
        "idx_postings_company", "job_postings", ["company_id"], unique=False
    )
    op.create_index(
        "idx_postings_title_hash", "job_postings", ["title_hash"], unique=False
    )
    op.create_index(
        "idx_postings_work_model", "job_postings", ["work_model"], unique=False
    )
    op.create_table(
        "user_search_queries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("site", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("added_reason", sa.Text(), nullable=True),
        sa.Column("retired_reason", sa.Text(), nullable=True),
        sa.Column(
            "postings_found", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "positive_labels", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "query_text"),
    )
    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "key"),
    )
    op.create_table(
        "user_watchlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "crawl_priority", sa.Integer(), server_default=sa.text("5"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("added_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "company_id"),
    )
    op.create_index(
        "idx_watchlist_active", "user_watchlist", ["user_id", "active"], unique=False
    )
    op.create_index(
        "idx_watchlist_company", "user_watchlist", ["company_id"], unique=False
    )
    op.create_index("idx_watchlist_user", "user_watchlist", ["user_id"], unique=False)
    op.create_table(
        "job_posting_locations",
        sa.Column("posting_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["posting_id"], ["job_postings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("posting_id", "location_id"),
    )
    op.create_index(
        "idx_jpl_location", "job_posting_locations", ["location_id"], unique=False
    )
    op.create_index(
        "idx_jpl_posting", "job_posting_locations", ["posting_id"], unique=False
    )
    op.create_table(
        "user_classifier_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("posting_id", sa.Integer(), nullable=False),
        sa.Column("classifier_score", sa.Float(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"], ["classifier_versions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["posting_id"], ["job_postings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "posting_id"),
    )
    op.create_index(
        "idx_cls_scores_posting", "user_classifier_scores", ["posting_id"], unique=False
    )
    op.create_index(
        "idx_cls_scores_user", "user_classifier_scores", ["user_id"], unique=False
    )
    op.create_table(
        "user_enriched_postings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("posting_id", sa.Integer(), nullable=False),
        sa.Column("fit_score", sa.Integer(), nullable=True),
        sa.Column("role_tier", sa.Text(), nullable=True),
        sa.Column("fit_reason", sa.Text(), nullable=True),
        sa.Column("key_requirements", sa.Text(), nullable=True),
        sa.Column(
            "enriched_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["posting_id"], ["job_postings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "posting_id"),
    )
    op.create_index(
        "idx_enriched_posting", "user_enriched_postings", ["posting_id"], unique=False
    )
    op.create_index(
        "idx_enriched_user", "user_enriched_postings", ["user_id"], unique=False
    )
    op.create_table(
        "user_labels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("posting_id", sa.Integer(), nullable=False),
        sa.Column("signal", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "labeled_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "label_source", sa.Text(), server_default=sa.text("'user'"), nullable=False
        ),
        sa.CheckConstraint(
            "signal IN ('positive','negative','applied','skip')",
            name="ck_user_labels_signal",
        ),
        sa.ForeignKeyConstraint(
            ["posting_id"], ["job_postings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "posting_id", "signal"),
    )
    op.create_index("idx_labels_posting", "user_labels", ["posting_id"], unique=False)
    op.create_index("idx_labels_user", "user_labels", ["user_id"], unique=False)
    op.create_table(
        "user_posting_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("posting_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'new'"), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('new','seen','applied','rejected','archived')",
            name="ck_posting_status_status",
        ),
        sa.ForeignKeyConstraint(
            ["posting_id"], ["job_postings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "posting_id"),
    )
    op.create_index(
        "idx_posting_status_posting",
        "user_posting_status",
        ["posting_id"],
        unique=False,
    )
    op.create_index(
        "idx_posting_status_status",
        "user_posting_status",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_posting_status_user", "user_posting_status", ["user_id"], unique=False
    )
    op.create_table(
        "user_similarity_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("posting_id", sa.Integer(), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["posting_id"], ["job_postings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "posting_id"),
    )
    op.create_index(
        "idx_sim_scores_posting", "user_similarity_scores", ["posting_id"], unique=False
    )
    op.create_index(
        "idx_sim_scores_user", "user_similarity_scores", ["user_id"], unique=False
    )
    op.create_index(
        "idx_sim_scores_value",
        "user_similarity_scores",
        ["user_id", "similarity_score"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_sim_scores_value", table_name="user_similarity_scores")
    op.drop_index("idx_sim_scores_user", table_name="user_similarity_scores")
    op.drop_index("idx_sim_scores_posting", table_name="user_similarity_scores")
    op.drop_table("user_similarity_scores")
    op.drop_index("idx_posting_status_user", table_name="user_posting_status")
    op.drop_index("idx_posting_status_status", table_name="user_posting_status")
    op.drop_index("idx_posting_status_posting", table_name="user_posting_status")
    op.drop_table("user_posting_status")
    op.drop_index("idx_labels_user", table_name="user_labels")
    op.drop_index("idx_labels_posting", table_name="user_labels")
    op.drop_table("user_labels")
    op.drop_index("idx_enriched_user", table_name="user_enriched_postings")
    op.drop_index("idx_enriched_posting", table_name="user_enriched_postings")
    op.drop_table("user_enriched_postings")
    op.drop_index("idx_cls_scores_user", table_name="user_classifier_scores")
    op.drop_index("idx_cls_scores_posting", table_name="user_classifier_scores")
    op.drop_table("user_classifier_scores")
    op.drop_index("idx_jpl_posting", table_name="job_posting_locations")
    op.drop_index("idx_jpl_location", table_name="job_posting_locations")
    op.drop_table("job_posting_locations")
    op.drop_index("idx_watchlist_user", table_name="user_watchlist")
    op.drop_index("idx_watchlist_company", table_name="user_watchlist")
    op.drop_index("idx_watchlist_active", table_name="user_watchlist")
    op.drop_table("user_watchlist")
    op.drop_table("user_settings")
    op.drop_table("user_search_queries")
    op.drop_index("idx_postings_work_model", table_name="job_postings")
    op.drop_index("idx_postings_title_hash", table_name="job_postings")
    op.drop_index("idx_postings_company", table_name="job_postings")
    op.drop_table("job_postings")
    op.drop_table("crawl_runs")
    op.drop_table("users")
    op.drop_table("system_settings")
    op.drop_index("idx_locations_state", table_name="locations")
    op.drop_index("idx_locations_region", table_name="locations")
    op.drop_index("idx_locations_country", table_name="locations")
    op.drop_index("idx_locations_city", table_name="locations")
    op.drop_index("idx_locations_canonical", table_name="locations")
    op.drop_table("locations")
    op.drop_table("companies")
    op.drop_table("classifier_versions")
    op.drop_index("idx_agent_actions_time", table_name="agent_actions")
    op.drop_index("idx_agent_actions_run", table_name="agent_actions")
    op.drop_table("agent_actions")
    # ### end Alembic commands ###
