"""add_ranking_pipeline

Revision ID: 538837880514
Revises: 4596e16062f9
Create Date: 2026-05-06 13:57:10.737374

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "538837880514"
down_revision: Union[str, Sequence[str], None] = "4596e16062f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("config_hash", sa.Text(), nullable=False),
        sa.Column("config_json", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("config_hash"),
    )
    op.create_index(
        "idx_pc_user_active", "pipeline_configs", ["user_id", "is_active"], unique=False
    )
    op.create_table(
        "user_ranking_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("posting_id", sa.Integer(), nullable=False),
        sa.Column("pipeline_config_id", sa.Integer(), nullable=False),
        sa.Column("composite_score", sa.Float(), nullable=False),
        sa.Column("component_scores", sa.Text(), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_config_id"], ["pipeline_configs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["posting_id"], ["job_postings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "posting_id", "pipeline_config_id"),
    )
    op.create_index(
        "idx_ranking_config",
        "user_ranking_scores",
        ["pipeline_config_id"],
        unique=False,
    )
    op.create_index(
        "idx_ranking_score",
        "user_ranking_scores",
        ["user_id", "composite_score"],
        unique=False,
    )
    op.create_index(
        "idx_ranking_user_posting",
        "user_ranking_scores",
        ["user_id", "posting_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ranking_user_posting", table_name="user_ranking_scores")
    op.drop_index("idx_ranking_score", table_name="user_ranking_scores")
    op.drop_index("idx_ranking_config", table_name="user_ranking_scores")
    op.drop_table("user_ranking_scores")
    op.drop_index("idx_pc_user_active", table_name="pipeline_configs")
    op.drop_table("pipeline_configs")
    # ### end Alembic commands ###
