"""add_company_description

Revision ID: a09b5faf35b6
Revises: 538837880514
Create Date: 2026-05-16 17:36:08.635967

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a09b5faf35b6"
down_revision: Union[str, Sequence[str], None] = "538837880514"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "companies", sa.Column("description_source", sa.Text(), nullable=True)
    )
    op.create_check_constraint(
        "ck_companies_description_source",
        "companies",
        "description_source IN ('wikipedia','website','manual','pending')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_companies_description_source", "companies")
    op.drop_column("companies", "description_source")
    op.drop_column("companies", "description")
    # ### end Alembic commands ###
